- hosts: wordpresssite
  vars:
    srcdir: /mnt/e/dev/weather/weatherstnapi/subsWH1080
    targdir: ~/mmwebsite/subwh1080
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/MQtoFile.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/mqConfig.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getWeatherData.sh', dest: '{{targdir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/stopGW.sh', dest: '{{targdir}}/', mode: '754', backup: yes }
#    - {src: '{{srcdir}}/install.sh', dest: '{{targdir}}/', mode: '754', backup: yes }
#    - {src: '{{srcdir}}/getweather.service', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{targdir}}/', mode: '644', backup: yes }

  - name: update broker
    ansible.builtin.replace:
      path: '{{targdir}}/mqConfig.py'
      regexp: "someserver.net"
      replace: "themcintyres.ddns.net"

  - name: update mqport 
    ansible.builtin.replace:
      path: '{{targdir}}/mqConfig.py'
      regexp: "1883"
      replace: "9883"
