- hosts: weatherpi
  vars:
    srcdir: /mnt/e/dev/weatherstnapi/weatherapi
  tasks:
  - name: import prod variables
    include_vars: local-vars.yml

  - name: Ensures {{apidir}} exists
    file: path={{apidir}} state=directory  

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [aws, local]
    with_items:
    - {src: '{{srcdir}}/weatherapi.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getLastData.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/apirequirements.txt', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/startup.sh', dest: '{{apidir}}/', mode: '754', backup: yes }
