- hosts: wxsatpi
  vars:
    srcdir: /mnt/e/dev/energy/weatherdata
  tasks:
  - name: import prod variables
    include_vars: local-vars.yml

  - name: Ensures {{fwddir}} exists
    file: path={{fwddir}} state=directory  
    tags: [aws, local]

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [aws, local]
    with_items:
    - {src: '{{srcdir}}/weatherFwd.py', dest: '{{fwddir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/fwdrequirements.txt', dest: '{{fwddir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/runWeatherFwd.sh', dest: '{{fwddir}}/', mode: '754', backup: yes }
